### ISSUE TITLE
I get the following error on the newst version 1.1.5

### ISSUE THREAD

**Issue by UHAXM1** [taylorbobaylor/TrailerDownloader#31]
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetAllMoviesInfo'.
      System.ArgumentNullException: Value cannot be null. (Parameter 'input')
         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
         at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /Users/taylorchristian/repos/TrailerDownloader/TrailerDownloader/SignalRHubs/MovieHub.cs:line 135
         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /Users/taylorchristian/repos/TrailerDownloader/TrailerDownloader/SignalRHubs/MovieHub.cs:line 57
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

**Comment by UHAXM1** [comment]
Ok I found the issue.
Some of my movie directories had sub directories like "Subs" and "Subtitles", they only included the srt files and nothing else, this was the cause of the issue, I found the issue around line 107 of the MovieHub.cs file, I changed it to read the following.

            foreach (var subDirectory in subDirectories)
            {
                if (Directory.GetDirectories(subDirectory).Length <= 0) continue;
                if (!subDirectory.Contains("Subs")) continue;
                if (!subDirectory.Contains("Subtitles")) continue;

                _movieDirectories.Add(subDirectory);
                hasSubdirectories = true;
            }

I found this in the code I downloaded (version 1.1.5 souce zip), however when I look at the file in the master branch it is diffrent, the master branch code is not the same as the code in the zip file. So I am unsure as to what I should do next,
I have compiled my changes and tested, and it fixes the issue.
Taylorbobatlow can you please advise.

**Comment by taylorbobaylor** [comment]
Hey @UHAXM1! Thanks for looking into it. I must've forgotten to update the release with the latest.
If you'd like to make a PR with your changes I'll take a look 😊

**Comment by UHAXM1** [comment]
Hi Taylor,

I will submit my changes but could you please sync your release first 
then I will update it.

Regards,

UHAX

**Comment by UHAXM1** [comment]
Sorry that's not what I ment, if I go into the code on the master branch it's still out of date, the compiled exe and the zipped source code are both up-to-date. You need to push the changes you have made to the master branch.
-------- Original message --------From: Taylor Christian ***@***.***> Date: 5/05/23  04:16  (GMT+12:00) To: taylorbobaylor/TrailerDownloader ***@***.***> Cc: UHAXM1 ***@***.***>, Mention ***@***.***> Subject: Re: [taylorbobaylor/TrailerDownloader] I get the following error on the newst version 1.1.5 (Issue #31) 
Here ya go. I just published from master branch and updated here

**Comment by UHAXM1** [comment]
I have attached a screenshot with the issue highlighted.

Regards,

Screenshot

**Comment by taylorbobaylor** [comment]
Ahhhh I see what you're saying. Thanks. I made a new release. GitHub automatically puts the `source code.zip` when you make the release so I just had to make a new one.
https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.6

**Comment by killmark-prog** [comment]
> Ahhhh I see what you're saying. Thanks. I made a new release. GitHub automatically puts the `source code.zip` when you make the release so I just had to make a new one. https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.6

I'm not sure if you've updated the TrailerDownloaderWindows.zip as the error still occurs.

**Comment by UHAXM1** [comment]
I just checked the source code for 1.1.6, it's still not correct, look at the pic I sent and compare the code,  once you have the correct code in place I will submit my changes then we can do a build.
-------- Original message --------From: killmark-prog ***@***.***> Date: 15/05/23  01:36  (GMT+12:00) To: taylorbobaylor/TrailerDownloader ***@***.***> Cc: UHAXM1 ***@***.***>, Mention ***@***.***> Subject: Re: [taylorbobaylor/TrailerDownloader] I get the following error on the newst version 1.1.5 (Issue #31) 

Ahhhh I see what you're saying. Thanks. I made a new release. GitHub automatically puts the source code.zip when you make the release so I just had to make a new one. https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.6

I'm not sure if you've updated the TrailerDownloaderWindows.zip as the error still occurs.

**Comment by taylorbobaylor** [comment]
@UHAXM1, @killmark-prog  Sorry I'm not understanding the problem... The latest version is working for me with no issues. And the source code zip on latest release is exact same as master branch.....

Master branch:
<img width="623" alt="image" src="https://github.com/taylorbobaylor/TrailerDownloader/assets/25238885/cef75756-8687-4e9f-a6c2-e05c938d193f">

Source code.zip:
<img width="629" alt="image" src="https://github.com/taylorbobaylor/TrailerDownloader/assets/25238885/2252dc52-53c0-47f2-8388-b3dc61f24680">

**Comment by killmark-prog** [comment]
![image](https://github.com/taylorbobaylor/TrailerDownloader/assets/55586720/071eaa89-75f0-4418-ae0a-042e44080cc2)

**Comment by taylorbobaylor** [comment]
@killmark-prog It looks like something is wrong with one of your directories. Is the app crashing when this happens or what is the UI doing?

**Comment by killmark-prog** [comment]
> 

Apologies, your correct.

From what I can see, if I have a folder with a trailer already in it, but their is no corresponding movie file then I get that error message and it will crash and stop looking for movie files.

**Comment by UHAXM1** [comment]
Ok I have uploaded the source to google drive, here is the link

https://drive.google.com/file/d/1RIOEWqLE9LBFNd4LhUh3t_tDwB-4bvIk/view?usp=sharing

The above link is to the code I downloaded from GitHub on the 04/05/23, 
about 11 days ago, please look at the MovieHub.cs file, lines 94 to 122, 
these changes were made by you, Taylor, but you never pushed them to the 
main branch. The code only ever existed in the Source zip and the 
compiled .exe.

You need to push these changes to the main branch, THEN, I will update 
the code with my fix.

The reason I don't want to push the code I have linked myself is because 
I have only looked at the MovieHub.cs, I don't know if you made changes 
to other files.

Please look at the code in the zip file, I suggest you push the changes 
to the master branch, please note I have not made any changes to the zip 
file, it is as I downloaded it.



Regards,

UHAX

**Comment by taylorbobaylor** [comment]
@UHAXM1 Thanks for the explanation! I made a new branch and replaced it with what you uploaded. You can use this branch to now make your changes and then make a PR into master branch.
https://github.com/taylorbobaylor/TrailerDownloader/tree/UHAX

**Comment by UHAXM1** [comment]
I have submitted my changes and a pull request.Regards,
-------- Original message --------From: Taylor Christian ***@***.***> Date: 15/05/23  03:03  (GMT+12:00) To: taylorbobaylor/TrailerDownloader ***@***.***> Cc: UHAXM1 ***@***.***>, Mention ***@***.***> Subject: Re: [taylorbobaylor/TrailerDownloader] I get the following error on the newst version 1.1.5 (Issue #31) 
@UHAXM1 Thanks for the explanation! I made a new branch and replaced it with what you uploaded. You can use this branch to now make your changes and then make a PR into master branch.
https://github.com/taylorbobaylor/TrailerDownloader/tree/UHAX

**Comment by taylorbobaylor** [comment]
@UHAXM1  I merged your changes into master and created a release [here](https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.7). Can you please test?

**Comment by UHAXM1** [comment]
Hey,I have tested version 1.1.7, my fix to skip subtitle directories is working.Please note, I have found a new bug (its been in all versions).You can read about it here.https://github.com/taylorbobaylor/TrailerDownloader/issues/33Regards,
-------- Original message --------From: Taylor Christian ***@***.***> Date: 21/05/23  13:38  (GMT+12:00) To: taylorbobaylor/TrailerDownloader ***@***.***> Cc: UHAXM1 ***@***.***>, Mention ***@***.***> Subject: Re: [taylorbobaylor/TrailerDownloader] I get the following error on the newst version 1.1.5 (Issue #31) 
@UHAXM1  I merged your changes into master and created a release here. Can you please test?

**Comment by taylorbobaylor** [comment]
Awesome, I will close this one out. Still working on the major refactor and will update the release once I have that finished 😊
